[package]
name = "secrets-auth-userpass"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
secrets-core.workspace = true
tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
argon2 = { version = "0.5", features = ["password-hash"] }
password-hash = { version = "0.5", features = ["getrandom"] }
